name: Auto Kayak Open/Close

on:
  schedule:
    - cron: '0 12 * * *'  # 8:00 AM UTC
    - cron: '0 19 * * *'  # 3:00 PM UTC
  workflow_dispatch:

jobs:
  update-kayak-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set kayak status based on time
        run: |
          hour=$(date -u +"%H")
          if [ "$hour" -eq 12 ]; then
            STATUS="open"
          else
            STATUS="closed"
          fi

          echo "Updating kayaks to $STATUS"

          cat <<EOF > status.json
          {
            "sun_ridge": "$(jq -r .sun_ridge status.json || echo 'closed')",
            "commons": "$(jq -r .commons status.json || echo 'closed')",
            "point": "$(jq -r .point status.json || echo 'closed')",
            "aquatic": "$(jq -r .aquatic status.json || echo 'closed')",
            "kayaks": "$STATUS"
          }
EOF

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add status.json
          git commit -m "Auto update kayak status to $STATUS"
          git push
